### ISSUE TITLE
nano上buildEngine报错

### ISSUE THREAD

**Issue by nightdyw-tech** [CaoWGG/TensorRT-YOLOv4#47]
您好，我用的是jetson nano 自带Tensorrt 6.0 cuda 10.0
按照步骤运行 ./buildEngine时
报错信息为：terminate called after throwing an instance of 'thrust::system::system_error'
what(): parallel_for failed: no kernel image is available for execution on the device
请问是否有解决方案，谢谢

**Comment by nightdyw-tech** [comment]
已解决，cmakelist内set(GPU_ARCHS 61)需要根据具体配置调整，如何查看对应信息可以看https://blog.csdn.net/zong596568821xp/article/details/106411024
